name: Alfie Baxter-Davies
favicon: null
layout_spectrum: 0.4660336070228368
typography_spectrum: 0.38448195112869143
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.22522564115934074
  lightness: 0.8174456527922302
  saturation: 0.574534649727866
  rhythmicContrast: 0.8912666123360395
purpose: []
