name: Alfie Baxter-Davies
favicon: null
layout_spectrum: 0.25261
typography_spectrum: 0.38448195112869143
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b2b2b4'
    - '#efeeec'
    - '#1f232e'
    - '#d64c44'
    - '#ff846e'
  brandStrength: 0.1875
  lightness: 0.8174456527922302
  saturation: 0.574534649727866
  rhythmicContrast: 0.8912666123360395
purpose: []
